### ISSUE TITLE
how to run it in gpu environment?

### ISSUE THREAD

**Issue by TITC** [lucasleesw/PCANet_python_ver#1]
Thanks for your Jupiter notebooks, but when I run it in google colab I found it hasn't use GPU.

![image](https://user-images.githubusercontent.com/35098797/107966014-3eb2d280-6fe6-11eb-8a3a-4e78e54d9ab1.png)

could you give me some suggestion to solve this problem?

**Comment by lucasleesw** [comment]
Hi, unfortunately our code dose not support GPU training. We use google colab because of their large RAM.
